= Overview
== Introduction and Scope

This technical white paper describes the architecture for a Zimbra Collaboration Suite (ZCS) implementation based on typical usage patterns for Small to Medium Business (SMB) customers with approximately 1,000 users. It should not be used to extrapolate to larger deployments or beyond the parameters show in Table 1 of the Sizing Assumptions.  The configurations shown will work for physical and virtual server deployments. However, Zimbra recommends a virtualized deployment using vSphere for the SMB customer.

This document does not cover detailed:

*	OS level selection or configuration.
*	Storage Area Network (SAN) configuration.
* Vendor-specific requirements with hardware. Integration requirements are discussed for a Split Domain configuration, but other integration requirements such as provisioning; application SMTP connectivity, etc. are not discussed.

Three scenarios are shown for customers that fall into categories of small, medium, or heavy email usage. The usage patterns referred to are based on email volumes (number of messages sent and received) and hardware performance typically found in SMB business environments.  Messaging system administrators should use the appropriate tools within the legacy environment to confirm their parameters fall into one of these categories. While ZCS can easily support a typical configuration on a single physical server, today’s SMB customers can take advantage of Zimbra’s architectural features such as proxy services and redundant MTA’s deployed in virtualized configurations to increase availability and flexibility in deployment options.

A highly available, cost effective infrastructure for email and collaboration can be achieved with Zimbra when used in conjunction with VMware vSphere and a SAN. 

Most Small-to-Medium Businesses today do not require archiving solutions. However, Archiving has been included in this architecture to demonstrate how it can be easily added to support litigation hold or discovery requirements.

The ZCS deployment is for the following solution requirements:

* Email, Address Book, Calendar, and Shared Documents and Folders.
* Easy scalability.
* Utilization of High Availability through vSphere and redundant services.
* Superior user experience.

Installations of Zimbra in the SMB range may require support of split domain mail routing during a migration period from legacy platforms to Zimbra or will migrate using the flash-cut approach. 

* The Split Domain configuration for email delivery enables email users in a single domain to reside on different email systems and allows for incremental migrations from a legacy platform to a new platform. During the migration process, one system is designated as the “primary” mail store and is responsible for receiving and routing mail for the domain (zm-train.com). The other system is considered the “secondary” mail store.  Split domain configuration and migration tools are covered elsewhere.
* “Flash-cut” refers to moving all users from the legacy environment to Zimbra during the shortest time frame possible.

== Intended Audience
This document is intended to be used by: 
* IT System Administrators with advanced-level Messaging experience
* Zimbra Partners

== Services to Be Deployed
In most cases, services deployed on legacy email platforms must be supported on Zimbra. While not all deployments require all services, this architecture assumes you will need to support the following:

* HTTPS
* POP3
* IMAP/IMAPS
* SMTP
* Mobile Connectivity (Blackberry, iPhones, Windows Mobile)

Users typically access a ZCS implementation through the Zimbra Web Client (ZWC) but may connect to the existing environment through multiple clients, which are listed below. ZCS supports connectivity through multiple clients and can be configured to support most standards based clients. The Zimbra Proxy service can provide connectivity for most clients to both the Zimbra Collaboration Server and legacy platforms during the migration phase if needed.
* Zimbra Desktop & Zimbra Connector for Outlook (ZCO): If a customer requires offline access to collaboration functionality during travel or network outages, Zimbra Desktop or Outlook with ZCO may be deployed to support this functionality. ZCO communicates with the Zimbra Proxy or Mailbox Server over HTTPS.

* IMAP: Some customer environments require IMAP access for users or programmatic functions.  This functionality can be provided by the Zimbra environment through standard configuration. 

* Mobile Devices: Mobile connectivity for iPhones and Windows Mobile devices may be provided using the Zimbra Mobile option. A Zimbra specific Blackberry Enterprise Server (BES) running the Zimbra Connector for Blackberry can be established to provide Blackberry connectivity.  Zimbra recommends one BES server for up to 200 BES users.
