= Storage Design

Disk operations traditionally represent the bottleneck for performance in the Zimbra environment and have the biggest impact on the user experience. Since email is write intensive, dedicated, high performance drives in RAID 1 or RAID 1+0 configurations typically provide the best throughput.  
Deployment of a SAN, while not required, provides the foundation for tools like vMotion to migrate virtual servers between physical servers and achieve High Availability goals. However, utilization of a SAN when used for multiple applications may create I/O contention and negatively impact Zimbra performance (i.e., if you have other applications running on the same SAN storage, it will negatively impact ZCS performance).  
Customers should allocate storage from the SAN for the primary message store, index storage, MySQL database storage, and redolog storage for mailbox servers. Zimbra binaries, log files, secondary message storage, and backups will be allocated from the same storage. For MTA/Proxy services, all software can be installed as part of the root partition on allocated virtual disk.
Customer should use Hierarchical Storage Management (HSM) in Zimbra. Secondary message stores will be created on the SAN, configured as a separate datastore in VMware, and designated as the “current” secondary message store from the Zimbra Administration Console.  Secondary volumes can reside on lower costs, larger disks such as 750 GB 7200 RPM SATA drives.
While SAN performance varies with the amount of cache allocated to volume groups, a minimum number of spindles should be allocated to the volume groups used for the mailbox server in order to ensure adequate performance during normal loads.
Since backups can represent high IOPs requirements and must be completed during non-business hours, adequate IOPs capacity (disk spindles) must be allocated to the backup partitions. The backup partition should be on a separate physical SAN environment or physical RAID group.
